/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PSN;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author aleja
 */
public class PSNplayers extends javax.swing.JFrame {
    PSNUser psn ;
    Entry users;
    boolean active = false;
    /**
     * Creates new form PSNplayers
     */
    public PSNplayers()  {
        initComponents();
        psn = new PSNUser();
        
   

        loadUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
      private void loadUsers() {
        active = false;
        users = psn.users.entry;
        usersCombo.removeAllItems();

        while (users == null) {
            System.out.println("entra ");
            usersCombo.addItem(users.username);
            users = users.siguiente;
        }

        active = true;
        updateText();
        
        
        

    }
      
      
      
    private void updateText() {

        String name = (String) usersCombo.getSelectedItem();
        playerInfoText.setText(psn.playerInfo(name));
        System.out.println("Actualizo");

    }  
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addDialogUsernameInput = new javax.swing.JTextField();
        addDialogAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        trophDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        trophUserCombo = new javax.swing.JComboBox<>();
        trophTypeCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        gameNameTexxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        trophNameText = new javax.swing.JTextField();
        saveTrophBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addUser = new javax.swing.JButton();
        delUser = new javax.swing.JButton();
        addTrophy = new javax.swing.JButton();
        usersCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerInfoText = new javax.swing.JTextArea();

        jLabel3.setText("Username");

        addDialogAdd.setText("Agregar");
        addDialogAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDialogAddMouseClicked(evt);
            }
        });
        addDialogAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDialogAddActionPerformed(evt);
            }
        });

        jLabel1.setText("Agregar Usuarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(addDialogAdd))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(36, 36, 36)
                                .addComponent(addDialogUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDialogUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addComponent(addDialogAdd)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Tipo");

        jLabel8.setText("Usuario");

        trophUserCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        trophTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platino", "Oro", "Plata", "Bronce", " " }));

        jLabel6.setText("Nombre del Juego");

        jLabel7.setText("Nombre del Juego Trofeo");

        saveTrophBtn.setText("Agregar Trofeo");
        saveTrophBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveTrophBtnMouseClicked(evt);
            }
        });

        jLabel2.setText("Agregar Trofeo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(gameNameTexxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(trophNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saveTrophBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trophTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trophUserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trophUserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trophTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameNameTexxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trophNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveTrophBtn)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout trophDialogLayout = new javax.swing.GroupLayout(trophDialog.getContentPane());
        trophDialog.getContentPane().setLayout(trophDialogLayout);
        trophDialogLayout.setHorizontalGroup(
            trophDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        trophDialogLayout.setVerticalGroup(
            trophDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addUser.setText("Agregar Usuario");
        addUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserMouseClicked(evt);
            }
        });

        delUser.setText("Eliminar Usuario");
        delUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delUserMouseClicked(evt);
            }
        });
        delUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delUserActionPerformed(evt);
            }
        });

        addTrophy.setText("Agregar Trofeo");
        addTrophy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTrophyMouseClicked(evt);
            }
        });

        usersCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "jeff", "Item 2", "Item 3", "Item 4" }));
        usersCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                usersComboItemStateChanged(evt);
            }
        });
        usersCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersComboActionPerformed(evt);
            }
        });

        playerInfoText.setEditable(false);
        playerInfoText.setColumns(20);
        playerInfoText.setLineWrap(true);
        playerInfoText.setRows(5);
        playerInfoText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(playerInfoText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(delUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(addTrophy)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addUser)
                            .addComponent(delUser)
                            .addComponent(addTrophy))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserMouseClicked
        // TODO add your handling code here:
        addDialogUsernameInput.setText("");
        addDialog.pack();
        addDialog.setVisible(true);
    }//GEN-LAST:event_addUserMouseClicked

    private void delUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delUserMouseClicked
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar el usuario actual?");

        if (op != 0) {
            return;
        }
        try {
        String username = (String) usersCombo.getSelectedItem();
        System.out.println("se elimino" + username);
        psn.deactivateUser(username);
        loadUsers();
        } catch (Exception e) {
        }

       
    }//GEN-LAST:event_delUserMouseClicked

    private void addTrophyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTrophyMouseClicked
        // TODO add your handling code here:

        if (psn.tamano == 0) {
            JOptionPane.showMessageDialog(null, "Agregue usuarios!");
            return;
        }

        trophNameText.setText("");
        gameNameTexxt.setText("");
        updateTrophUsers();
        trophDialog.pack();
        trophDialog.setVisible(true);
    }//GEN-LAST:event_addTrophyMouseClicked

    private void usersComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_usersComboItemStateChanged
        // TODO add your handling code here:
        if (!active) {
            return;
        }
        updateText();
    }//GEN-LAST:event_usersComboItemStateChanged

    private void delUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delUserActionPerformed

    private void addDialogAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDialogAddMouseClicked
        // TODO add your handling code here:
        try {
        String username = addDialogUsernameInput.getText();
        active = false;
        if (username.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos");
            return;
        }

        boolean res = psn.addUser(username);
       
        if (res) {
            System.out.println(res);
            JOptionPane.showMessageDialog(null, "Se ha agregado el usuario.");
            addDialog.dispose();
            loadUsers();
        }
        active = true;
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_addDialogAddMouseClicked

    private void saveTrophBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTrophBtnMouseClicked
        // TODO add your handling code here:

        Trophy trophType;
        String selectedType = (String) trophTypeCombo.getSelectedItem();

        if (selectedType.equals("Platino")) {
            trophType = Trophy.PLATINO;
        } else if (selectedType.equals("Oro")) {
            trophType = Trophy.ORO;
        } else if (selectedType.equals("Plata")) {
            trophType = Trophy.PLATA;
        } else {
            trophType = Trophy.BRONCE;
        }

        String gameName = gameNameTexxt.getText();
        String trophName = trophNameText.getText();
        String username = (String) trophUserCombo.getSelectedItem();

        if (gameName.isBlank() || trophName.isBlank()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
            return;
        }

        psn.addTrophieTo(username, gameName, trophName, trophType);
        trophDialog.dispose();
        updateText();
    }//GEN-LAST:event_saveTrophBtnMouseClicked

    private void addDialogAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDialogAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDialogAddActionPerformed

    private void usersComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usersComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PSNplayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PSNplayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PSNplayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PSNplayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                     new PSNplayers().setVisible(true);
                } catch (Exception e) {
                }
               
            }
        });
    }
    
    private void updateTrophUsers() {
        Entry e = psn.users.entry;
        trophUserCombo.removeAllItems();

        while (e != null) {
            trophUserCombo.addItem(e.username);
            e = e.siguiente;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addDialog;
    private javax.swing.JButton addDialogAdd;
    private javax.swing.JTextField addDialogUsernameInput;
    private javax.swing.JButton addTrophy;
    private javax.swing.JButton addUser;
    private javax.swing.JButton delUser;
    private javax.swing.JTextField gameNameTexxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea playerInfoText;
    private javax.swing.JButton saveTrophBtn;
    private javax.swing.JDialog trophDialog;
    private javax.swing.JTextField trophNameText;
    private javax.swing.JComboBox<String> trophTypeCombo;
    private javax.swing.JComboBox<String> trophUserCombo;
    private javax.swing.JComboBox<String> usersCombo;
    // End of variables declaration//GEN-END:variables
}


